dorado_exec: "/work/microbiome/sw/dorado-v0.9.1/dorado-0.9.1-linux-x64/bin/dorado"
pod5_sample_list: "/work/microbiome/arctic/data/20240910/dorado-v0.9.0/test_snake/pod5_sample_list.txt"  # text file of POD5 sample filepaths
output_dir: "/" # path to output directory
models_directory: "/work/microbiome/sw/dorado-v0.9.1/models"
kit_name: "SQK-NBD114-24" # set barcoding kit as required
base_mods: # set base modifications as required separated by spaces e.g. "4mC_5mC 6mA"
